projetos/controle-estoque-salesforce/force-app/main/default/objects/Fornecedor__c/Fornecedor__c.object-meta.xml
<CustomObject>
    <label>Fornecedor</label>
    <nameField>
        <label>Nome do fornecedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fornecedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Produto__c/Produto__c.object-meta.xml
<CustomObject>
    <label>Produto</label>
    <nameField>
        <label>Nome do Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

projetos/controle-estoque-salesforce/force-app/main/default/objects/Produto__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <label>Fornecedor</label>
    <referenceTo>Fornecedor__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

projetos/controle-estoque-salesforce/force-app/main/default/objects/Produto__c/fields/Quantidade_Em_Estoque__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_Em_Estoque__c</fullName>
    <label>Quantidade em estoque</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

projetos/controle-estoque-salesforce/force-app/main/default/objects/Produto__c/fields/Quantidade_Minima__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_Minima__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Define a quantidade mínima em estoque para este produto.</description>
    <label>Quantidade Mínima</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

projetos/controle-estoque-salesforce/force-app/main/default/classes/ProdutosParaComprarController.cls
public with sharing class ProdutosParaComprarController {
    @AuraEnabled(cacheable=true)
    public static List<Produto__c> getProdutosAbaixoDoMinimo() {
        List<Produto__c> produtos = [
            SELECT Id, Name, Quantidade_Em_Estoque__c, Quantidade_Minima__c, Fornecedor__c, Fornecedor__r.Name
            FROM Produto__c
            WHERE Quantidade_Minima__c != null
            ORDER BY Name
        ];

        List<Produto__c> produtosAbaixoDoMinimo = new List<Produto__c>();
        for (Produto__c produto : produtos) {
            if (produto.Quantidade_Em_Estoque__c != null &&
                produto.Quantidade_Em_Estoque__c < produto.Quantidade_Minima__c) {
                produtosAbaixoDoMinimo.add(produto);
            }
        }
        return produtosAbaixoDoMinimo;
    }
}