projetos/passagens-salesforce/force-app/main/default/objects/Aeroporto__c/Aeroporto__c.object-meta.xml
<CustomObject>
    <label>Aeroporto</label>
    <nameField><label>Nome do Aeroporto</label><type>Text</type><length>120</length></nameField>
    <pluralLabel>Aeroportos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

projetos/passagens-salesforce/force-app/main/default/objects/Aeroporto__c/fields/Estado_r__c.field-meta.xml
<CustomField>
    <fullName>Estado_r__c</fullName><label>Estado</label><type>Lookup</type><referenceTo>Estado__c</referenceTo><relationshipName>Estado</relationshipName><relationshipLabel>Estado</relationshipLabel>
</CustomField>

projetos/passagens-salesforce/force-app/main/default/objects/Aeroporto__c/fields/Sigla__c.field-meta.xml
<CustomField>
    <fullName>Sigla__c</fullName><label>Sigla</label><length>3</length><type>Text</type>
</CustomField>

projetos/passagens-salesforce/force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField><label>Numero do Ticket</label><type>AutoNumber</type><displayFormat>T-{00000}</displayFormat><startingNumber>1</startingNumber></nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

projetos/passagens-salesforce/force-app/main/default/objects/Ticket__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName><label>Conta</label><type>Lookup</type><referenceTo>Account</referenceTo><relationshipName>Tickets</relationshipName><relationshipLabel>Tickets</relationshipLabel>
</CustomField>

projetos/passagens-salesforce/force-app/main/default/objects/Ticket__c/fields/Voo_Ida__c.field-meta.xml
<CustomField>
    <fullName>Voo_Ida__c</fullName><label>Voo de Ida</label><type>Lookup</type><referenceTo>Voo__c</referenceTo><relationshipName>Tickets_Ida</relationshipName><relationshipLabel>Tickets de Ida</relationshipLabel>
</CustomField>

projetos/passagens-salesforce/force-app/main/default/objects/Ticket__c/fields/Voo_Volta__c.field-meta.xml
<CustomField>
    <fullName>Voo_Volta__c</fullName><label>Voo de Volta</label><type>Lookup</type><referenceTo>Voo__c</referenceTo><relationshipName>Tickets_Volta</relationshipName><relationshipLabel>Tickets de Volta</relationshipLabel>
</CustomField>

projetos/passagens-salesforce/force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <label>Voo</label>
    <nameField><label>Numero do Voo</label><type>Text</type><length>40</length></nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

projetos/passagens-salesforce/force-app/main/default/objects/Voo__c/fields/Aeroporto_Chegada__c.field-meta.xml
<CustomField>
    <fullName>Aeroporto_Chegada__c</fullName><label>Aeroporto de Chegada</label><type>Lookup</type><referenceTo>Aeroporto__c</referenceTo><relationshipName>Aeroporto_Chegada</relationshipName><relationshipLabel>Aeroporto de Chegada</relationshipLabel>
</CustomField>

projetos/passagens-salesforce/force-app/main/default/objects/Voo__c/fields/Aeroporto_Partida__c.field-meta.xml
<CustomField>
    <fullName>Aeroporto_Partida__c</fullName><label>Aeroporto de Partida</label><type>Lookup</type><referenceTo>Aeroporto__c</referenceTo><relationshipName>Aeroporto_Partida</relationshipName><relationshipLabel>Aeroporto de Partida</relationshipLabel>
</CustomField>

projetos/passagens-salesforce/force-app/main/default/objects/Voo__c/fields/Data_Partida__c.field-meta.xml
<CustomField>
    <fullName>Data_Partida__c</fullName><label>Data de Partida</label><type>Date</type>
</CustomField>

projetos/passagens-salesforce/force-app/main/default/objects/Voo__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName><label>Valor</label><precision>16</precision><scale>2</scale><type>Currency</type>
</CustomField>

projetos/academia-salesforce/force-app/main/default/classes/TicketsController.cls
// force-app/main/default/classes/TicketsController.cls
public with sharing class TicketsController {

    @AuraEnabled(cacheable=true)
    public static List<Aeroporto__c> getAeroportos(String search) {
        search = ''; // Conforme visível nas imagens mais recentes

        return [SELECT Id, Name, Estado_r__c.Name, Sigla__c
                FROM Aeroporto__c
                WHERE Name LIKE :search OR
                      Estado_r__c.Name LIKE :search OR
                      Sigla__c LIKE :search
                WITH SECURITY_ENFORCED];
    }

    // 2020-12-15
    private static Date dateParse(String dateString) {
        List<String> dt = dateString.split('-');
        Date dtResult = Date.newInstance(Integer.valueOf(dt.get(0)), Integer.valueOf(dt.get(1)), Integer.valueOf(dt.get(2)));
        return dtResult;
    }

    @AuraEnabled
    public static String getVoos(String aeroportoOrigem, String aeroportoDestino, String dataPartida, String dataRetorno) {
        Date dtPartida = dateParse(dataPartida);
        Date dtRetorno = dateParse(dataRetorno);

        List<Voo__c> voosOrigem = [SELECT Id, Name, Aeroporto_Chegada__r.Sigla__c, Aeroporto_Partida__r.Sigla__c, Valor__c
                                   FROM Voo__c
                                   WHERE Data_Partida__c = :dtPartida AND Aeroporto_Partida__c = :aeroportoOrigem
                                   WITH SECURITY_ENFORCED];

        List<Voo__c> voosDestino = [SELECT Id, Name, Aeroporto_Chegada__r.Sigla__c, Aeroporto_Partida__r.Sigla__c, Valor__c
                                    FROM Voo__c
                                    WHERE Data_Partida__c = :dtRetorno AND Aeroporto_Chegada__c = :aeroportoDestino
                                    WITH SECURITY_ENFORCED];

        Map<Id, Voo__c> result = new Map<Id, Voo__c>();
        for(Voo__c vooOrigem : voosOrigem) {
            result.put(vooOrigem.Id, vooOrigem);
        }
        for(Voo__c vooDestino : voosDestino) {
            result.put(vooDestino.Id, vooDestino);
        }
        return JSON.serialize(result);
    }

    @AuraEnabled
    public static Ticket__c createTicket(String accountId, String vooIdId, String vooVoltaId) {
        if (Schema.SObjectType.Ticket__c.isCreateable()) {
            Ticket__c ticket = new Ticket__c();
            if (Schema.SObjectType.Ticket__c.fields.Account__c.isCreateable()) {
                ticket.Account__c = accountId;
            }
            if (Schema.SObjectType.Ticket__c.fields.Voo_Ida__c.isCreateable()) {
                ticket.Voo_Ida__c = vooIdId;
            }
            if (Schema.SObjectType.Ticket__c.fields.Voo_Volta__c.isCreateable()) {
                ticket.Voo_Volta__c = vooVoltaId;
            }
            insert ticket;
            return ticket;
        } else {
            throw new AuraHandledException('Você nao tem permissao para criar um ticket, contacte o Administrador');
        }
    }
}